### ISSUE TITLE
Starting pgsql service message never disappears in June update

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio-postgresql#138]
- Update Azure Data Studio to June release
- Restart application
- See that "Starting pgsql service" stays in the toolbar forever
- You can still connect as usual

![image](https://user-images.githubusercontent.com/10819925/59122993-09994600-8911-11e9-8a3a-2490ef935141.png)

- There's no output under pgsqlToolsService

This was reported by a customer - see https://twitter.com/digitalduquette/status/1136974420638142464. I think this warrants investigation & planning to get an update going, right @akamath46297 ?

**Comment by DigitalDuquette** [comment]
I posted a comment on [issue 108](https://github.com/microsoft/azuredatastudio-postgresql/issues/108) as well, which I've placed below.

<img width="1426" alt="Screen Shot 2019-06-07 at 9 46 47 AM" src="https://user-images.githubusercontent.com/47231954/59108569-33e70580-8909-11e9-8f13-3d033057e7dd.png">
This issue has started for me as well on the latest release of macOS (10.14.5).  The message doesn't error out it hangs at 'Starting pgsql service' 
![Screen Shot 2019-06-07 at 8 29 27 AM](https://user-images.githubusercontent.com/47231954/59104017-62abae80-88fe-11e9-9dfa-7ef4736032cd.png)

I've tried uninstalling and reinstalling the extension. 

` ERR The "path" argument must be of type string. Received type object: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at toAbsolutePath (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:207868:52)
    at resolveIconPath (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:207894:13)
    at ExtensionPoint.extensionsRegistry_1.ExtensionsRegistry.registerExtensionPoint.setHandler.extensions [as _handler] (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:207846:13)
    at ExtensionPoint._handle (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:207237:22)
    at ExtensionPoint.acceptUsers (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:207230:18)
    at Function._handleExtensionPoint (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257961:28)
    at ExtensionService._rehandleExtensionPoints (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257432:38)
    at ExtensionService.<anonymous> (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257405:22)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5933:58)
    at ZoneDelegate.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:388:26)
    at Zone.run (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:138:43)
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:872:34
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:188:47)
    at drainMicroTaskQueue (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:595:35)`

**Comment by akamath46297** [comment]
I am taking a look at this
