### ISSUE TITLE
Issue with Token / PWD in Azure AAD login

### ISSUE THREAD

**Issue by jaketclarke** [microsoft/azuredatastudio-postgresql#185]
Short summary:
An attempt at saving the token for Azure AAD managed PostgreSQL login will fail ungracefully with a stack trace

Steps to repeat:
1. install the PostgreSQL extension
2. generate a token following the steps from: https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication, repeated below for brevity:
3. in a command prompt:
    1. az login
    2. az account get-access-token --resource https://ossrdbms-aad.database.windows.net
4: in azure data studio, create a new postgres connection, and enter:
    1. Server name - an Azure PostGIS managed instance e.g foobar.postgres.database.azure.com
    2. User name - your azure username e.g yourname@yourtenant.onmicrosoft.com@foobar
    3. Enter your token as password
    4. Press 'remember password'

Expected Behaviour:
1. Store the token, or:
2. Error nicely telling the user that's the issue

Actual Behaviour:
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The password has exceeded 512 bytes
at Microsoft.SqlTools.Credentials.Win32.Win32Credential.Save() in D:\a\1\s\src\Microsoft.SqlTools.Credentials\Credentials\Win32\Win32Credential.cs:line 208
at Microsoft.SqlTools.Credentials.Win32.Win32CredentialStore.Save(Credential credential) in D:\a\1\s\src\Microsoft.SqlTools.Credentials\Credentials\Win32\Win32CredentialStore.cs:line 57
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.SqlTools.Credentials.CredentialService.SaveCredentialAsync(Credential credential) in D:\a\1\s\src\Microsoft.SqlTools.Credentials\Credentials\CredentialService.cs:line 137
at Microsoft.SqlTools.Credentials.CredentialService.HandleRequest[T](Func`1 handler, RequestContext`1 requestContext, String requestType) in D:\a\1\s\src\Microsoft.SqlTools.Credentials\Credentials\CredentialService.cs:line 173

**Comment by lfittl-msft** [comment]
@jaketclarke Thanks for the report - this looks like a new issue.

We are actually in the process of releasing a new experience that avoids copy and pasting the token manually. We're currently tracking one more bug on that release, but once thats fixed we'll have a seamless integration so you can simply select the Azure Account you'd like to login with.

I'll update this once the new release is fully out, thanks for your patience in getting this resolved!

**Comment by gflores1023** [comment]
@jaketclarke new release is out. 

https://cloudblogs.microsoft.com/sqlserver/2020/03/23/the-march-2020-release-of-azure-data-studio-is-now-available/
