### ISSUE TITLE
pgToolsService is unable to start on Debian

### ISSUE THREAD

**Issue by mubaidr** [microsoft/azuredatastudio-postgresql#256]
Unable to activate 

###Environment details
Version: 1.25.3
Commit: b277eafb8f5328ea26c6edfddd1999292ac27937
Date: 2021-02-09T22:55:06.361Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.0-3-amd64

microsoft.azuredatastudio-postgresql extension
0.2.7

```bash
python3 --version
Python 3.9.1
```
###Error
```bash
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

###Impact
- Cannot open connection to Azure Arc postgresql instance (DB is up and running).
- Restarting ADS and uninstall/install extension does not solve the issue.
- Insiders version has same issue. 
- I checked and /opt/hostedtoolcache/Python/ is empty
- Python 3.9.1 is installed globally.

**Comment by mubaidr** [comment]
Possible workaround for this issue: https://github.com/microsoft/pgtoolsservice/issues/239#issuecomment-653665504

```bash
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

**Comment by SteveWithAQ** [comment]
reproduced on Linux Mint 20 (debian/ubuntu derivative)

**Comment by SteveWithAQ** [comment]
> Possible workaround for this issue: [microsoft/pgtoolsservice#239 (comment)](https://github.com/microsoft/pgtoolsservice/issues/239#issuecomment-653665504)
> 
> ```shell
> sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
> ```

This workaround appears to work for me. Thanks!

**Comment by mksuni** [comment]
closing the issue as it is resolved.
