### ISSUE TITLE
Error on opening New query connected as role; postgres 

### ISSUE THREAD

**Issue by mcarter106** [microsoft/azuredatastudio-postgresql#290]
When opening a new query window after connecting to a PostgreSQL instance as a role.  This error does not occur when connecting as the instance user only as a role.  
Receive the following:  
It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
--- Logging error ---
Traceback (most recent call last):
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 89, in _bg_refresh
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 175, in refresh_functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in <listcomp>
  File "D:\a\1\s\ossdbtoolsservice\language\query\pg_lightweight_metadata.py", line 252, in functions
psycopg2.ProgrammingError: column p.proisagg does not exist
LINE 8:                         p.proisagg is_aggregate,
                                ^
HINT:  Perhaps you meant to reference the column "p.prolang".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 994, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 840, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 577, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 338, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 884, in _bootstrap
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 864, in run
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 110, in _bg_refresh
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1343, in exception
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1337, in error
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1444, in _log
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1454, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1516, in callHandlers
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 865, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1072, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1000, in emit
Message: 'Error during metadata refresh: {0}'
Arguments: (ProgrammingError('column p.proisagg does not exist\nLINE 8:                         p.proisagg is_aggregate,\n                                ^\nHINT:  Perhaps you meant to reference the column "p.prolang".\n',),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 89, in _bg_refresh
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 175, in refresh_functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in <listcomp>
  File "D:\a\1\s\ossdbtoolsservice\language\query\pg_lightweight_metadata.py", line 252, in functions
psycopg2.ProgrammingError: column p.proisagg does not exist
LINE 8:                         p.proisagg is_aggregate,
                                ^
HINT:  Perhaps you meant to reference the column "p.prolang".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 994, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 840, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 577, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 338, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 884, in _bootstrap
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 864, in run
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 110, in _bg_refresh
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1343, in exception
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1337, in error
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1444, in _log
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1454, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1516, in callHandlers
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 865, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1072, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1000, in emit
Message: 'Error during metadata refresh: {0}'
Arguments: (ProgrammingError('column p.proisagg does not exist\nLINE 8:                         p.proisagg is_aggregate,\n                                ^\nHINT:  Perhaps you meant to reference the column "p.prolang".\n',),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 89, in _bg_refresh
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 175, in refresh_functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in functions
  File "D:\a\1\s\ossdbtoolsservice\language\metadata_executor.py", line 92, in <listcomp>
  File "D:\a\1\s\ossdbtoolsservice\language\query\pg_lightweight_metadata.py", line 252, in functions
psycopg2.ProgrammingError: column p.proisagg does not exist
LINE 8:                         p.proisagg is_aggregate,
                                ^
HINT:  Perhaps you meant to reference the column "p.prolang".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 994, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 840, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 577, in format
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 338, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 884, in _bootstrap
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\threading.py", line 864, in run
  File "D:\a\1\s\ossdbtoolsservice\language\completion_refresher.py", line 110, in _bg_refresh
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1343, in exception
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1337, in error
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1444, in _log
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1454, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1516, in callHandlers
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 865, in handle
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1072, in emit
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 1000, in emit
Message: 'Error during metadata refresh: {0}'
Arguments: (ProgrammingError('column p.proisagg does not exist\nLINE 8:                         p.proisagg is_aggregate,\n                                ^\nHINT:  Perhaps you meant to reference the column "p.prolang".\n',),)
[Error - 10:29:41 AM] Request connection/listdatabases failed.
  Message: 'NoneType' object has no attribute 'list_databases'
  Code: 0

**Comment by DaeunYim** [comment]
We were not able to reproduce this issue. Please provide detailed production steps if you are still seeing the issue after updating both ADS (1.45.1) and PostgreSQL extension (0.5) versions.
