### ISSUE TITLE
pgtoolservice test tests.query.test_in_memory_result_set failing intermittently 

### ISSUE THREAD

**Issue by akamath46297** [microsoft/azuredatastudio-postgresql#79]
2018-12-08T00:24:34.8843052Z FAIL: test_save_as (tests.query.test_in_memory_result_set.TestInMemoryResultSet)
2018-12-08T00:24:34.8843192Z ----------------------------------------------------------------------
2018-12-08T00:24:34.8843264Z Traceback (most recent call last):
2018-12-08T00:24:34.8843386Z   File "D:\a\1\s\tests\query\test_in_memory_result_set.py", line 120, in test_save_as
2018-12-08T00:24:34.8843486Z     mock_file_factory.get_writer.assert_called_once_with(params.file_path)
2018-12-08T00:24:34.8843572Z   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\unittest\mock.py", line 825, in assert_called_once_with
2018-12-08T00:24:34.8843710Z     return self.assert_called_with(*args, **kwargs)
2018-12-08T00:24:34.8843781Z   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\unittest\mock.py", line 805, in assert_called_with
2018-12-08T00:24:34.8843878Z     raise AssertionError('Expected call: %s\nNot called' % (expected,))
2018-12-08T00:24:34.8844003Z AssertionError: Expected call: get_writer('somepath')
2018-12-08T00:24:34.8844435Z Not called
2018-12-08T00:24:34.8844483Z 
2018-12-08T00:24:34.8844575Z Name

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. Reopen if issue persists, thank you.
